import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";
import MouseTracker from "@/component/MourseTracker";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <MouseTracker />

        {children}
      </body>
    </html>
  );
}
